### ISSUE TITLE
2020.11.03亲测无法访问

### ISSUE THREAD

**Issue by czl0325** [TurboHK/google-access-helper#1]
2020.11.03亲测无法访问

**Comment by TurboHK** [comment]
1）請將問題描述的更具體，謝謝。
2）此版本僅是將程式翻譯為繁體中文，並未改動程式核心部分原始碼。有關程式内部錯誤或異常，請聯絡軟體原作者。

**Comment by czl0325** [comment]
插件安装后，还是无法打开谷歌应用商店，chrome://extensions/  进入后，左下角打开谷歌网上应用店，要下载插件，但是打不开。

**Comment by TurboHK** [comment]
請問擴充程式主畫面（彈出式視窗）是否有顯示連線成功？

**Comment by czl0325** [comment]
![Uploading image.png…]()

**Comment by czl0325** [comment]
<img width="645" alt="image" src="https://user-images.githubusercontent.com/2100549/98326809-0b4aca00-202d-11eb-89fa-02e9ee24d895.png">

**Comment by TurboHK** [comment]
![20201115135948](https://user-images.githubusercontent.com/59258447/99178113-f7991500-274a-11eb-853b-5de40c030ef0.png)
程式本身有提示無法連線嗎？（圖為連線正常時的畫面）
